apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig.yaml

resources:
- service.yaml
- manifests.yaml
- storage_quota_webhook_configuration.yaml

patches:
- path: manifests_label_patch.yaml
- path: webhookcainjection_patch.yaml
