apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: supervisor-properties-reader-binding
roleRef:
  name: supervisor-properties-reader
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: default
  namespace: vmware-system-vmop
