# nameReference teaches Kustomize which fields represent a resource name.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    path: spec/conversion/webhook/clientConfig/service/name

# namespace teaches Kustomize which fields represent a resource namespace.
namespace:
- kind: CustomResourceDefinition
  group: apiextensions.k8s.io
  path: spec/conversion/webhook/clientConfig/service/namespace
  create: false
